const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const form = $('#lyrics-form'), songTitle = $('#song-title'), lyrics = $('#lyrics'), status = $('#status');
const card = $('#verse-card'), backgroundImage = $('#verse-background'), refEl = $('#verse-reference'), textEl = $('#verse-text'), versionEl = $('#verse-version');
const bg = $('#background-color'), fg = $('#text-color'), titleColor = $('#title-color'), titleSize = $('#title-size'), titleSizeValue = $('#title-size-value'), fontFamily = $('#font-family'), fontTrigger = $('#font-family-trigger'), fontTriggerText = $('#font-family-text'), fontOptions = $('#font-family-options'), transparent = $('#transparent-bg');
const dots = $('#slide-dots'), previousButton = $('#previous-slide'), nextButton = $('#next-slide'), downloadButton = $('#download-button'), downloadPptButton = $('#download-ppt-button'), downloadButtonLabel = $('#download-button-label'), downloadPptButtonLabel = $('#download-ppt-button-label'), downloadNote = $('#download-note'), presentButton = $('#present-button');
const backgroundChoices = $$('[data-background]'), backgroundImageTrigger = $('#background-image-trigger'), backgroundImageText = $('#background-image-text'), backgroundImagePreview = $('#background-image-preview'), backgroundImageOptions = $('#background-image-options'), solidColorOption = $('#solid-color-option');

const STORAGE_KEY = 'proyecta-cantos-presentacion';
const FONT_OPTIONS = [{ id: 'manrope', label: 'Manrope · minimalista' }, { id: 'cormorant', label: 'Cormorant · clásica' }];
const BACKGROUND_OPTIONS = {
  'warm-light': { label: 'Luz cálida', src: '../assets/backgrounds/luz-calida.webp' }, mountains: { label: 'Montañas suaves', src: '../assets/backgrounds/montanas-suaves.webp' }, cross: { label: 'Cruz difusa', src: '../assets/backgrounds/cruz-difusa.webp' }, bible: { label: 'Biblia abstracta', src: '../assets/backgrounds/biblia-abstracta.webp' }, texture: { label: 'Textura nocturna', src: '../assets/backgrounds/textura-nocturna.webp' }, landscape: { label: 'Paisaje sereno', src: '../assets/backgrounds/paisaje-sereno.webp' }
};
let slides = [{ reference: '', text: 'Pega la letra de un canto y genera láminas listas para proyectar.' }];
let currentSlide = 0, hasGeneratedLyrics = false, selectedBackgroundId = 'solid', presentationWindow = null;
const presentationChannel = 'BroadcastChannel' in window ? new BroadcastChannel(STORAGE_KEY) : null;

function setStatus(message, kind = '') { status.textContent = message; status.className = `status ${kind}`.trim(); }
function cleanTitle() { return songTitle.value.trim() || 'ProyectaCantos'; }
function filenamePart(value) { return value.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'canto'; }
function state() { return { slides, currentSlide, appearance: { background: bg.value, backgroundImage: selectedBackgroundId, text: fg.value, titleColor: titleColor.value, titleSize: Number(titleSize.value), transparent: transparent.checked, font: fontFamily.value } }; }
function publish() { const nextState = state(); try { localStorage.setItem(STORAGE_KEY, JSON.stringify(nextState)); } catch { /* Storage can be unavailable. */ } presentationChannel?.postMessage(nextState); }

function wrapLine(line, maximum = 46) {
  const result = []; let current = '';
  line.trim().split(/\s+/).forEach(word => { const candidate = current ? `${current} ${word}` : word; if (current && candidate.length > maximum) { result.push(current); current = word; } else current = candidate; });
  if (current) result.push(current); return result;
}
function makeSlides(value) {
  const sections = [], source = value.replace(/\r\n?/g, '\n').split('\n'); let section = [];
  source.forEach(raw => { const line = raw.trim().replace(/\s+/g, ' '); if (!line) { if (section.length) { sections.push(section); section = []; } } else section.push(...wrapLine(line)); });
  if (section.length) sections.push(section);
  const generated = sections.flatMap(lines => { const groups = [], rest = [...lines]; while (rest.length) groups.push(rest.splice(0, rest.length === 4 ? 2 : Math.min(3, rest.length))); return groups.map(group => ({ reference: '', text: group.join('\n') })); });
  const title = songTitle.value.trim();
  if (title) generated.unshift({ reference: title, text: '', isTitle: true });
  return generated;
}

function closeFontOptions() { fontOptions.hidden = true; fontTrigger.setAttribute('aria-expanded', 'false'); }
function closeBackgroundOptions() { backgroundImageOptions.hidden = true; backgroundImageTrigger.setAttribute('aria-expanded', 'false'); }
function updateFontOptions() {
  fontOptions.innerHTML = '';
  FONT_OPTIONS.forEach(option => { const button = document.createElement('button'); button.type = 'button'; button.className = 'font-option'; button.dataset.font = option.id; button.setAttribute('role', 'option'); button.textContent = option.label; button.addEventListener('click', () => { fontFamily.value = option.id; closeFontOptions(); updateAppearance(); }); fontOptions.append(button); });
}
function updateTitleSize() { const scale = Math.max(1, Math.min(2, Number(titleSize.value) / 100 || 1.2)), label = `${titleSize.value}%`; titleSizeValue.value = label; titleSizeValue.textContent = label; titleSize.setAttribute('aria-valuetext', label); titleSize.style.setProperty('--title-size-progress', `${titleSize.value - 100}%`); refEl.style.setProperty('--reference-min', `${Math.round(16 * scale)}px`); refEl.style.setProperty('--reference-preferred', `${(1.65 * scale).toFixed(3)}vw`); refEl.style.setProperty('--reference-max', `${Math.round(27.2 * scale)}px`); }
function updateBackgroundChoices() { const background = BACKGROUND_OPTIONS[selectedBackgroundId]; backgroundChoices.forEach(choice => { const active = choice.dataset.background === selectedBackgroundId; choice.classList.toggle('is-active', active); choice.setAttribute('aria-pressed', String(active)); }); solidColorOption.classList.toggle('is-active', !background); backgroundImageText.textContent = background?.label || 'Elegir imagen'; backgroundImagePreview.hidden = !background; if (background && backgroundImagePreview.getAttribute('src') !== background.src) backgroundImagePreview.src = background.src; }
function updateBackgroundImage() { const background = BACKGROUND_OPTIONS[selectedBackgroundId], hasImage = Boolean(background && !transparent.checked); card.classList.toggle('has-background-image', hasImage); backgroundImage.hidden = !hasImage; if (hasImage && backgroundImage.getAttribute('src') !== background.src) backgroundImage.src = background.src; }
function selectBackground(id) { selectedBackgroundId = BACKGROUND_OPTIONS[id] ? id : 'solid'; transparent.checked = false; updateBackgroundChoices(); closeBackgroundOptions(); updateAppearance(); }
function selectSolidBackground() { selectedBackgroundId = 'solid'; transparent.checked = false; updateBackgroundChoices(); updateAppearance(); }
function fitText() { const width = card.clientWidth || 640, sizes = [.055, .05, .045, .04, .035, .03].map(ratio => `${Math.max(10, Math.round(width * ratio))}px`); for (const size of sizes) { card.style.setProperty('--verse-size', size); if (textEl.scrollHeight <= textEl.clientHeight) return; } }
function renderDots() { dots.innerHTML = ''; slides.forEach((_, index) => { const dot = document.createElement('button'); dot.type = 'button'; dot.className = 'slide-dot'; dot.setAttribute('aria-label', `Ver lámina ${index + 1} de ${slides.length}`); dot.setAttribute('aria-current', String(index === currentSlide)); dot.addEventListener('click', () => showSlide(index)); dots.append(dot); }); }
function updateActions() { const count = slides.length, pngLabel = `Descargar (${count} .png)`; downloadButtonLabel.textContent = pngLabel; downloadPptButtonLabel.textContent = `Descargar (${count} .ppt)`; downloadButton.setAttribute('aria-label', pngLabel); downloadPptButton.setAttribute('aria-label', `Descargar PPTX con ${count} diapositivas`); downloadNote.textContent = `${count} lámina${count === 1 ? '' : 's'} preparada${count === 1 ? '' : 's'}.`; [downloadButton, downloadPptButton, presentButton].forEach(button => { button.disabled = !hasGeneratedLyrics; }); }
function showSlide(index) { currentSlide = Math.max(0, Math.min(index, slides.length - 1)); const slide = slides[currentSlide]; const isTitle = Boolean(slide.reference && !slide.text); refEl.textContent = slide.reference; textEl.textContent = slide.text; versionEl.textContent = ''; card.classList.toggle('lyrics-only', !slide.reference); card.classList.toggle('title-only', isTitle); previousButton.disabled = currentSlide === 0; nextButton.disabled = currentSlide === slides.length - 1; renderDots(); requestAnimationFrame(() => { fitText(); publish(); }); }
function updateAppearance() { card.style.backgroundColor = transparent.checked ? 'transparent' : bg.value; updateBackgroundImage(); textEl.style.color = fg.value; refEl.style.color = titleColor.value; updateTitleSize(); const font = fontFamily.value === 'cormorant' ? 'Cormorant Garamond, Georgia, serif' : 'Manrope, Avenir, sans-serif'; [refEl, textEl, versionEl].forEach(element => { element.style.fontFamily = font; }); textEl.style.fontWeight = fontFamily.value === 'cormorant' ? '500' : '300'; fontTriggerText.textContent = FONT_OPTIONS.find(option => option.id === fontFamily.value)?.label || FONT_OPTIONS[0].label; fontOptions.querySelectorAll('.font-option').forEach(option => { const active = option.dataset.font === fontFamily.value; option.classList.toggle('is-active', active); option.setAttribute('aria-selected', String(active)); }); showSlide(currentSlide); }
function generate(event) { event.preventDefault(); const value = lyrics.value.trim(); if (!value) { setStatus('Pega la letra del canto antes de generar las láminas.', 'error'); lyrics.focus(); return; } slides = makeSlides(value); if (!slides.length) { setStatus('No encontramos líneas que se puedan proyectar. Revisa la letra e inténtalo nuevamente.', 'error'); return; } hasGeneratedLyrics = true; updateActions(); showSlide(0); setStatus(`${slides.length} lámina${slides.length === 1 ? '' : 's'} creada${slides.length === 1 ? '' : 's'} con 2 o 3 líneas por vista.`, 'success'); }

function presentationWindowFeatures(display) { const width = Math.max(720, Math.round(display?.availWidth || 1280)), height = Math.max(480, Math.round(display?.availHeight || 720)), position = display ? `,left=${Math.round(display.availLeft)},top=${Math.round(display.availTop)}` : ''; return `popup=yes,fullscreen=yes,resizable=yes,scrollbars=no,width=${width},height=${height}${position}`; }
function focusPresentation(presentation) { if (!presentation || presentation.closed) return; presentation.focus(); window.setTimeout(() => { if (!presentation.closed) presentation.focus(); }, 240); }
async function movePresentation(presentation) { try { const details = await window.getScreenDetails(); if (presentation.closed) return; const secondary = details.screens.find(display => display !== details.currentScreen) || details.screens.find(display => !display.isPrimary); if (!secondary) { setStatus('Edge detecta una sola pantalla. En Windows presiona Win + P, selecciona “Extender” y vuelve a presentar.', 'error'); return; } presentation.moveTo(Math.round(secondary.availLeft), Math.round(secondary.availTop)); presentation.resizeTo(Math.round(secondary.availWidth), Math.round(secondary.availHeight)); focusPresentation(presentation); setStatus('Salida enviada a la segunda pantalla. Usa pantalla completa si Edge lo solicita.', 'success'); } catch (error) { setStatus(error?.name === 'NotAllowedError' ? 'Permite a Edge administrar ventanas para enviar la salida a otra pantalla.' : 'No fue posible detectar las pantallas. Abre la web desde GitHub Pages (HTTPS) y verifica Edge.', 'error'); } }
function openPresentation() { if (!hasGeneratedLyrics) return; publish(); const presentation = presentationWindow && !presentationWindow.closed ? presentationWindow : window.open('output.html?fullscreen=1', `proyecta-cantos-output-${Date.now()}`, presentationWindowFeatures()); if (!presentation) { setStatus('El navegador bloqueó la ventana de presentación. Permite las ventanas emergentes e inténtalo nuevamente.', 'error'); return; } presentationWindow = presentation; focusPresentation(presentation); if (!window.isSecureContext) { setStatus('La ventana se abrió; para enviarla automáticamente a otra pantalla publica la web en HTTPS.', 'error'); return; } if (typeof window.getScreenDetails !== 'function') { setStatus('La ventana se abrió. Usa F11 en la pantalla de proyección si tu navegador no permite detectar monitores.', 'success'); return; } setStatus('Solicitando permiso para detectar pantallas…'); void movePresentation(presentation); }
const waitForPaint = () => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)));
async function waitForBackground() { if (backgroundImage.hidden || backgroundImage.complete) return; await new Promise(resolve => { backgroundImage.addEventListener('load', resolve, { once: true }); backgroundImage.addEventListener('error', resolve, { once: true }); }); }
async function exportSlide(index) { showSlide(index); await waitForPaint(); await waitForBackground(); const canvas = await html2canvas(card, { scale: 3, backgroundColor: transparent.checked ? null : bg.value, useCORS: true, logging: false }); const output = document.createElement('canvas'); output.width = 1920; output.height = 1080; output.getContext('2d').drawImage(canvas, 0, 0, 1920, 1080); return new Promise(resolve => output.toBlob(resolve, 'image/png')); }
async function downloadPngs() { if (!window.html2canvas) { setStatus('No se pudo cargar el generador de PNG. Revisa tu conexión.', 'error'); return; } const selected = currentSlide; downloadButton.disabled = true; try { for (let index = 0; index < slides.length; index += 1) { downloadButtonLabel.textContent = `Generando ${index + 1} de ${slides.length}…`; const blob = await exportSlide(index), link = document.createElement('a'); link.download = `${filenamePart(cleanTitle())}-${String(index + 1).padStart(2, '0')}.png`; link.href = URL.createObjectURL(blob); link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); } setStatus(`${slides.length} PNG descargado${slides.length === 1 ? '' : 's'}.`, 'success'); } catch { setStatus('No se pudieron generar todos los PNG. Inténtalo nuevamente.', 'error'); } finally { showSlide(selected); updateActions(); } }
function blobToDataUrl(blob) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(blob); }); }
async function downloadPptx() { if (!window.PptxGenJS || !window.html2canvas) { setStatus('No se pudo cargar el generador de PowerPoint. Revisa tu conexión.', 'error'); return; } const selected = currentSlide; downloadPptButton.disabled = true; try { const pptx = new PptxGenJS(); pptx.layout = 'LAYOUT_WIDE'; pptx.author = 'AriLabs'; pptx.subject = `Canto: ${cleanTitle()}`; pptx.title = `${cleanTitle()} | ProyectaCantos`; pptx.lang = 'es-CL'; for (let index = 0; index < slides.length; index += 1) { downloadPptButtonLabel.textContent = `Generando ${index + 1} de ${slides.length}…`; const pptSlide = pptx.addSlide(), imageData = await blobToDataUrl(await exportSlide(index)); if (!transparent.checked) pptSlide.background = { color: bg.value.replace('#', '') }; pptSlide.addImage({ data: imageData, x: 0, y: 0, w: 13.333, h: 7.5 }); } await pptx.writeFile({ fileName: `${filenamePart(cleanTitle())}-proyectacantos.pptx`, compression: true }); setStatus(`${slides.length} diapositiva${slides.length === 1 ? '' : 's'} exportada${slides.length === 1 ? '' : 's'} en PPTX.`, 'success'); } catch { setStatus('No se pudo generar el PPTX. Inténtalo nuevamente.', 'error'); } finally { showSlide(selected); updateActions(); } }

form.addEventListener('submit', generate);
songTitle.addEventListener('input', () => { if (!hasGeneratedLyrics) return; const title = songTitle.value.trim(), hasTitleSlide = slides[0]?.isTitle; if (hasTitleSlide && title) slides[0].reference = title; else if (hasTitleSlide) { slides.shift(); currentSlide = Math.max(0, currentSlide - 1); } else if (title) { slides.unshift({ reference: title, text: '', isTitle: true }); currentSlide += 1; } showSlide(currentSlide); });
document.addEventListener('pointerdown', event => { if (!event.target.closest('.font-picker')) closeFontOptions(); if (!event.target.closest('.background-image-picker')) closeBackgroundOptions(); });
fontTrigger.addEventListener('click', () => { const opening = fontOptions.hidden; fontOptions.hidden = !opening; fontTrigger.setAttribute('aria-expanded', String(opening)); });
backgroundImageTrigger.addEventListener('click', () => { const opening = backgroundImageOptions.hidden; backgroundImageOptions.hidden = !opening; backgroundImageTrigger.setAttribute('aria-expanded', String(opening)); });
[fg, titleColor, titleSize, fontFamily, transparent].forEach(control => control.addEventListener('input', updateAppearance));
bg.addEventListener('click', selectSolidBackground); bg.addEventListener('input', selectSolidBackground); backgroundChoices.forEach(choice => choice.addEventListener('click', () => selectBackground(choice.dataset.background)));
previousButton.addEventListener('click', () => showSlide(currentSlide - 1)); nextButton.addEventListener('click', () => showSlide(currentSlide + 1)); downloadButton.addEventListener('click', downloadPngs); downloadPptButton.addEventListener('click', downloadPptx); presentButton.addEventListener('click', openPresentation); window.addEventListener('resize', () => showSlide(currentSlide)); Object.values(BACKGROUND_OPTIONS).forEach(({ src }) => { const image = new Image(); image.src = src; });
updateFontOptions(); updateBackgroundChoices(); updateActions(); updateAppearance();
